App\Entity\Entry:
  type: entity
  repositoryClass: App\Repository\EntryRepository
  table: dsrt.entry
  indexes:
    name_index:
      columns: [ id ]
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    note:
      type: string
      length: 1024
      nullable: true
  manyToOne:
    user:
      targetEntity: User
      joinColumn:
        name: userId
        referencedColumnName: id
    workday:
      targetEntity: Workday
      joinColumn:
        name: workdayId
        referencedColumnName: id
