App\Entity\Meal:
  type: entity
  repositoryClass: App\Repository\MealRepository
  table: dsrt.meal
  indexes:
    name_index:
      columns: [ id ]
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 256
    link:
      type: string
      length: 1024
      nullable: true
    description:
      type: string
      length: 1024
      nullable: true
