App\Entity\User:
  type: entity
  repositoryClass: App\Repository\UserRepository
  table: dsrt.user
  indexes:
    name_index:
      columns: [ id ]
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 256
    email:
      type: string
      length: 180
      unique: true
    roles:
      type: json
    password:
      type: string
      length: 256
      nullable: true
  oneToMany:
    entries:
      targetEntity: Entry
      mappedBy: user
      cascase: ["remove"]
