entry:
  path: /entry
  controller: App\Controller\EntryController::index

entry_show:
  path: /entry/{id}
  controller: App\Controller\EntryController::showEntry

entry_show_all:
  path: entries
  controller: App\Controller\EntryController::showAllEntry

entry_on_date:
  path: /entries/{date}
  controller: App\Controller\EntryController::showEntriesOnDate

entry_create:
  path: /create/entry
  controller: App\Controller\EntryController::createEntry

entry_edit:
  path: /edit/entry/{id}
  controller: App\Controller\EntryController::editEntry

entry_delete:
  path: /delete/entry/{id}
  controller: App\Controller\EntryController::deleteEntry
